- name: Check file system partition configuration
  block:
    - name: Check if {{ item.target }} is a separate partition
      ansible.builtin.command: "findmnt -k {{ item.target }}"
      register: findmnt_result
      changed_when: false
      failed_when: false

    - name: Check {{ item.target }} mount options
      ansible.builtin.command: "findmnt -n -o OPTIONS {{ item.target }}"
      register: mount_options_result
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Set compliance status for {{ item.name }}
      set_fact:
        current_result: >-
          {{
            'PASS' if (
              findmnt_result.rc == 0 and
              (item.required_options is not defined or
               item.required_options.split(',') | difference(mount_options_result.stdout.split(',') | default([])) | length == 0)
            ) else 'FAIL'
          }}

    - name: Save compliance result for {{ item.name }}
      set_fact:
        cis_results: >-
          {{
            cis_results | combine({
              item.name: {
                'result': current_result,
                'cis_subsection': item.cis_subsection,
                'severity': item.severity
              }
            })
          }}
        passed_ids: "{{ passed_ids + [item.cis_subsection] if current_result == 'PASS' else passed_ids }}"
        failed_ids: "{{ failed_ids + [item.cis_subsection] if current_result == 'FAIL' else failed_ids }}"