- name: Split kernel modules for {{ item.name }}
  set_fact:
    module_list: "{{ item.target.split(',') | map('trim') | list }}"
    module_failed: false
  when: item.type == "checkKernalModule"

- name: Debug compliance result for {{ item.name }}
  debug:
    msg: "Compliance result for {{ item.name }} ({{ item.cis_subsection }}): {{ compliance_data[item.name] | default('Not found in compliance_data') }}"
  when: item.type == "checkKernalModule"

- name: Include remediation tasks for each kernel module under {{ item.name }}
  include_tasks:
    file: fix_single_kernel_module.yml
  loop: "{{ module_list }}"
  loop_control:
    loop_var: module
    label: "{{ module }}"
  when: item.type == "checkKernalModule" and compliance_data[item.name].result == "FAIL"

- name: Record remediation result for {{ item.name }}
  set_fact:
    passed_ids: "{{ passed_ids + [item.cis_subsection] if not module_failed else passed_ids }}"
    failed_ids: "{{ failed_ids + [item.cis_subsection] if module_failed else failed_ids }}"
  when: item.type == "checkKernalModule" and compliance_data[item.name].result == "FAIL"