- name: Remediate Package Management configuration
  block:
    - name: Init accumulator
      debug:
        var: compliance_data[item.name]

    - name: Init accumulator
      debug:
        var: item

    - name: Fixing for {{ item.cis_subsection }}  {{ item.name }}
      lineinfile:
        path: "{{ repo_file }}"
        regexp: "{{ item.select_value }}"
        line: "{{ item.target_value }}"
        backup: yes
      when: compliance_data[item.name].result == 'FAIL' 
      loop: "{{ compliance_data[item.name].files }}"
      register: repo_file_result
      loop_control:
        loop_var: repo_file
        label: "{{ repo_file }}"

    - name: debug
      ansible.builtin.debug:
        msg: "Remediation result for {{ item.name }} ({{ item.cis_subsection }}): {{ repo_file_result }}"
        
    - name: Record remediation result for {{ item.name }}
      set_fact:
        passed_ids: "{{ passed_ids + [item.cis_subsection] if not (repo_file_result is failed) else passed_ids }}"
        failed_ids: "{{ failed_ids + [item.cis_subsection] if (repo_file_result is failed) else failed_ids }}"

  when: (item.cis_subsection ) in [ '1.2.1.1', '1.2.1.2', '1.2.1.3' ] and (item.ignore_fix | default('') != 'true') 
  tags:
    - packageManagement

- name: Ensure Patches are Updated
  block:
    # - name: Init accumulator
    #   debug:
    #     var: compliance_data[item.name]

    # - name: Init accumulator
    #   debug:
    #     var: item

    - name: Fixing for {{ item.cis_subsection }}  {{ item.name }}
      shell: "{{ item.target_value }}"
      when: compliance_data[item.name].result == 'FAIL'
      register: patch_status
      failed_when: false
      ignore_errors: true

    - name: debug
      ansible.builtin.debug:
        msg: "Remediation result for {{ item.name }} ({{ item.cis_subsection }}): {{ patch_status }}"

    - name: Record remediation result for {{ item.name }}
      set_fact:
        passed_ids: "{{ passed_ids + [item.cis_subsection] if (patch_status.rc | default(1)) == 0 else passed_ids }}"
        failed_ids: "{{ failed_ids + [item.cis_subsection] if (patch_status.rc | default(1)) != 0 else failed_ids }}"

  when: (item.cis_subsection ) in [ '1.2.2.1' ] and (item.ignore_fix | default('') != 'true') 
  tags:
    - packageManagement


